[package]
name = "radio"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soapysdr = "0.3.1"
num-complex = "0.4"
anyhow = "1.0.69"
rand = "0.8.4"
rand_distr = "0.4.3"
rustfft = "6.1.0"

[dev-dependencies]
criterion = "0.4.0"
lazy_static = "1.4.0"

[[bench]]
name = "bench"
harness = false

[features]
mfsk = []
fsk = []
ask = []
bpsk = []
qpsk = []
